-- Script generated by Redgate Compare v1.48.1.2539


-- deployment: Dropping vw_user_summary...
DROP VIEW vw_user_summary;


-- deployment: Dropping vw_order_summary...
DROP VIEW vw_order_summary;


-- deployment: Dropping vw_customer_summary...
DROP VIEW vw_customer_summary;


-- deployment: Dropping subscription_workflow...
DROP TABLE subscription_workflow;


-- deployment: Dropping smedia_subscriber_post...
DROP TABLE smedia_subscriber_post;


-- deployment: Dropping smedia_subscriber_page...
DROP TABLE smedia_subscriber_page;


-- deployment: Dropping smedia_subscriber_friend...
DROP TABLE smedia_subscriber_friend;


-- deployment: Dropping smedia_subscriber_account...
DROP TABLE smedia_subscriber_account;


-- deployment: Dropping smedia_post_media...
DROP TABLE smedia_post_media;


-- deployment: Dropping smedia_post_insights...
DROP TABLE smedia_post_insights;


-- deployment: Dropping smedia_post_comment_replies...
DROP TABLE smedia_post_comment_replies;


-- deployment: Dropping smedia_post_comment...
DROP TABLE smedia_post_comment;


-- deployment: Dropping smedia_inbox_message...
DROP TABLE smedia_inbox_message;


-- deployment: Dropping sec_role_endpoint...
DROP TABLE sec_role_endpoint;


-- deployment: Dropping sec_ip_whitelist...
DROP TABLE sec_ip_whitelist;


-- deployment: Dropping sec_client_menu_group...
DROP TABLE sec_client_menu_group;


-- deployment: Dropping sec_app_build_version...
DROP TABLE sec_app_build_version;


-- deployment: Dropping qrtz_triggers.FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS...
ALTER TABLE qrtz_triggers DROP FOREIGN KEY FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS;


-- deployment: Dropping qrtz_simprop_triggers.FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS...
ALTER TABLE qrtz_simprop_triggers DROP FOREIGN KEY FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS;


-- deployment: Dropping qrtz_simprop_triggers...
DROP TABLE qrtz_simprop_triggers;


-- deployment: Dropping qrtz_simple_triggers.FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS...
ALTER TABLE qrtz_simple_triggers DROP FOREIGN KEY FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS;


-- deployment: Dropping qrtz_simple_triggers...
DROP TABLE qrtz_simple_triggers;


-- deployment: Dropping qrtz_scheduler_state...
DROP TABLE qrtz_scheduler_state;


-- deployment: Dropping qrtz_paused_trigger_grps...
DROP TABLE qrtz_paused_trigger_grps;


-- deployment: Dropping qrtz_locks...
DROP TABLE qrtz_locks;


-- deployment: Dropping qrtz_job_details...
DROP TABLE qrtz_job_details;


-- deployment: Dropping qrtz_fired_triggers...
DROP TABLE qrtz_fired_triggers;


-- deployment: Dropping qrtz_cron_triggers.FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS...
ALTER TABLE qrtz_cron_triggers DROP FOREIGN KEY FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS;


-- deployment: Dropping qrtz_cron_triggers...
DROP TABLE qrtz_cron_triggers;


-- deployment: Dropping qrtz_calendars...
DROP TABLE qrtz_calendars;


-- deployment: Dropping qrtz_blob_triggers...
DROP TABLE qrtz_blob_triggers;


-- deployment: Dropping promotion_wallet_rewards...
DROP TABLE promotion_wallet_rewards;


-- deployment: Dropping planner_drug...
DROP TABLE planner_drug;


-- deployment: Dropping pill_reminder_txn...
DROP TABLE pill_reminder_txn;


-- deployment: Dropping pill_reminder...
DROP TABLE pill_reminder;


-- deployment: Dropping pill_planner...
DROP TABLE pill_planner;


-- deployment: Dropping op_slot_session...
DROP TABLE op_slot_session;


-- deployment: Dropping op_slot_reminders...
DROP TABLE op_slot_reminders;


-- deployment: Dropping op_slot_pattern...
DROP TABLE op_slot_pattern;


-- deployment: Dropping op_slot_defs...
DROP TABLE op_slot_defs;


-- deployment: Dropping op_slot_booking...
DROP TABLE op_slot_booking;


-- deployment: Dropping op_payments...
DROP TABLE op_payments;


-- deployment: Dropping op_call_history...
DROP TABLE op_call_history;


-- deployment: Dropping notif_device_info...
DROP TABLE notif_device_info;


-- deployment: Dropping hospital_subscription...
DROP TABLE hospital_subscription;


-- deployment: Dropping hospital_master...
DROP TABLE hospital_master;


-- deployment: Dropping drug_dosage...
DROP TABLE drug_dosage;


-- deployment: Dropping driver_master...
DROP TABLE driver_master;


-- deployment: Dropping doctor_registration...
DROP TABLE doctor_registration;


-- deployment: Dropping doctor_qualification_docs...
DROP TABLE doctor_qualification_docs;


-- deployment: Dropping doctor_preferences...
DROP TABLE doctor_preferences;


-- deployment: Dropping doctor_master_id...
DROP TRIGGER doctor_master_id;


-- deployment: Dropping dd_stream_master...
DROP TABLE dd_stream_master;


-- deployment: Dropping dd_speciality_master...
DROP TABLE dd_speciality_master;


-- deployment: Dropping dd_relation_master...
DROP TABLE dd_relation_master;


-- deployment: Dropping dd_qualification_master...
DROP TABLE dd_qualification_master;


-- deployment: Dropping dd_medical_university...
DROP TABLE dd_medical_university;


-- deployment: Dropping dd_medical_council...
DROP TABLE dd_medical_council;


-- deployment: Dropping dd_language_master...
DROP TABLE dd_language_master;


-- deployment: Dropping dd_degree_master...
DROP TABLE dd_degree_master;


-- deployment: Dropping dd_currency_master...
DROP TABLE dd_currency_master;


-- deployment: Dropping customer_water_intake_reminder...
DROP TABLE customer_water_intake_reminder;


-- deployment: Dropping customer_subscription...
DROP TABLE customer_subscription;


-- deployment: Dropping customer_referral_reward...
DROP TABLE customer_referral_reward;


-- deployment: Dropping customer_referral_order...
DROP TABLE customer_referral_order;


-- deployment: Dropping customer_drug_plan...
DROP TABLE customer_drug_plan;


-- deployment: Dropping customer_drug_dosage...
DROP TABLE customer_drug_dosage;


-- deployment: Dropping customer_address...
DROP TABLE customer_address;


-- deployment: Dropping cpg_wallet_txn_type...
DROP TABLE cpg_wallet_txn_type;


-- deployment: Dropping cpg_wallet_txn...
DROP TABLE cpg_wallet_txn;


-- deployment: Dropping cpg_wallet_rewards...
DROP TABLE cpg_wallet_rewards;


-- deployment: Dropping cpg_wallet_bank_account...
DROP TABLE cpg_wallet_bank_account;


-- deployment: Dropping cpg_wallet_adjustments...
DROP TABLE cpg_wallet_adjustments;


-- deployment: Dropping cpg_wallet...
DROP TABLE cpg_wallet;


-- deployment: Dropping cpg_refund...
DROP TABLE cpg_refund;


-- deployment: Dropping cpg_referral_wallet_bonus...
DROP TABLE cpg_referral_wallet_bonus;


-- deployment: Dropping chatbot_response...
DROP TABLE chatbot_response;


-- deployment: Dropping bot_response...
DROP TABLE bot_response;


-- deployment: Dropping ambulance_booking...
DROP TABLE ambulance_booking;


-- deployment: Dropping sp_validate_slot_overlap...
DROP PROCEDURE sp_validate_slot_overlap;


-- deployment: Dropping sp_test_get_doctor_profiles...
DROP PROCEDURE sp_test_get_doctor_profiles;


-- deployment: Dropping sp_testget_doctor_profiles...
DROP PROCEDURE sp_testget_doctor_profiles;


-- deployment: Dropping sp_get_doctor_profiles...
DROP PROCEDURE sp_get_doctor_profiles;


-- deployment: Dropping sp_generate_username_suggestions...
DROP PROCEDURE sp_generate_username_suggestions;


-- deployment: Dropping wishlist_item.item_UNIQUE...
DROP INDEX item_UNIQUE ON wishlist_item;


-- deployment: Dropping wishlist_item...
DROP TABLE wishlist_item;


-- deployment: Dropping wishlist.name_UNIQUE...
DROP INDEX name_UNIQUE ON wishlist;


-- deployment: Dropping wishlist.id_UNIQUE...
DROP INDEX id_UNIQUE ON wishlist;


-- deployment: Dropping wishlist...
DROP TABLE wishlist;


-- deployment: Dropping warehouse_type_master.code...
DROP INDEX code ON warehouse_type_master;


-- deployment: Dropping warehouse_type_master...
DROP TABLE warehouse_type_master;


-- deployment: Dropping warehouse_type.code...
DROP INDEX code ON warehouse_type;


-- deployment: Dropping warehouse_type...
DROP TABLE warehouse_type;


-- deployment: Dropping warehouse_master.code...
DROP INDEX code ON warehouse_master;


-- deployment: Dropping warehouse_master...
DROP TABLE warehouse_master;


-- deployment: Dropping subscription_tier.id_UNIQUE...
DROP INDEX id_UNIQUE ON subscription_tier;


-- deployment: Dropping subscription_tier...
DROP TABLE subscription_tier;


-- deployment: Dropping subscription_plan.id_UNIQUE...
DROP INDEX id_UNIQUE ON subscription_plan;


-- deployment: Dropping subscription_plan.code_UNIQUE...
DROP INDEX code_UNIQUE ON subscription_plan;


-- deployment: Dropping subscription_plan...
DROP TABLE subscription_plan;


-- deployment: Dropping subscription_payment.id_UNIQUE...
DROP INDEX id_UNIQUE ON subscription_payment;


-- deployment: Dropping subscription_payment...
DROP TABLE subscription_payment;


-- deployment: Dropping subscription_package.id_UNIQUE...
DROP INDEX id_UNIQUE ON subscription_package;


-- deployment: Dropping subscription_package...
DROP TABLE subscription_package;


-- deployment: Dropping subscription_feature.id_UNIQUE...
DROP INDEX id_UNIQUE ON subscription_feature;


-- deployment: Dropping subscription_feature...
DROP TABLE subscription_feature;


-- deployment: Dropping stock_point.code...
DROP INDEX code ON stock_point;


-- deployment: Dropping stock_point...
DROP TABLE stock_point;


-- deployment: Dropping smedia_provider_post.id_UNIQUE...
DROP INDEX id_UNIQUE ON smedia_provider_post;


-- deployment: Dropping smedia_provider_post...
DROP TABLE smedia_provider_post;


-- deployment: Dropping shop_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON shop_master;


-- deployment: Dropping shop_master...
DROP TABLE shop_master;


-- deployment: Dropping sec_user_role_map.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_user_role_map;


-- deployment: Dropping sec_user_role_map...
DROP TABLE sec_user_role_map;


-- deployment: Dropping sec_user_master.username_UNIQUE...
DROP INDEX username_UNIQUE ON sec_user_master;


-- deployment: Dropping sec_user_master.mpin_UNIQUE...
DROP INDEX mpin_UNIQUE ON sec_user_master;


-- deployment: Dropping sec_user_master.mobile_number_UNIQUE...
DROP INDEX mobile_number_UNIQUE ON sec_user_master;


-- deployment: Dropping sec_user_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_user_master;


-- deployment: Dropping sec_user_master.email_id_UNIQUE...
DROP INDEX email_id_UNIQUE ON sec_user_master;


-- deployment: Dropping sec_user_master...
DROP TABLE sec_user_master;


-- deployment: Dropping sec_role_menu_link.role_group_link_id_unique...
DROP INDEX role_group_link_id_unique ON sec_role_menu_link;


-- deployment: Dropping sec_role_menu_link.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_role_menu_link;


-- deployment: Dropping sec_role_menu_link...
DROP TABLE sec_role_menu_link;


-- deployment: Dropping sec_role_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_role_master;


-- deployment: Dropping sec_role_master.code_UNIQUE...
DROP INDEX code_UNIQUE ON sec_role_master;


-- deployment: Dropping sec_role_master...
DROP TABLE sec_role_master;


-- deployment: Dropping sec_password_history.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_password_history;


-- deployment: Dropping sec_password_history...
DROP TABLE sec_password_history;


-- deployment: Dropping sec_login_history.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_login_history;


-- deployment: Dropping sec_login_history...
DROP TABLE sec_login_history;


-- deployment: Dropping sec_cta_menu_link_map.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_cta_menu_link_map;


-- deployment: Dropping sec_cta_menu_link_map...
DROP TABLE sec_cta_menu_link_map;


-- deployment: Dropping sec_client_page_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_client_page_master;


-- deployment: Dropping sec_client_page_master...
DROP TABLE sec_client_page_master;


-- deployment: Dropping sec_client_page_keyword.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_client_page_keyword;


-- deployment: Dropping sec_client_page_keyword...
DROP TABLE sec_client_page_keyword;


-- deployment: Dropping sec_client_menu_link.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_client_menu_link;


-- deployment: Dropping sec_client_menu_link...
DROP TABLE sec_client_menu_link;


-- deployment: Dropping sec_client_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_client_master;


-- deployment: Dropping sec_client_master...
DROP TABLE sec_client_master;


-- deployment: Dropping sec_client_cta.code_UNIQUE...
DROP INDEX code_UNIQUE ON sec_client_cta;


-- deployment: Dropping sec_client_cta...
DROP TABLE sec_client_cta;


-- deployment: Dropping sec_channel_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_channel_master;


-- deployment: Dropping sec_channel_master...
DROP TABLE sec_channel_master;


-- deployment: Dropping sec_api_service.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_api_service;


-- deployment: Dropping sec_api_service...
DROP TABLE sec_api_service;


-- deployment: Dropping sec_api_resource.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_api_resource;


-- deployment: Dropping sec_api_resource...
DROP TABLE sec_api_resource;


-- deployment: Dropping sec_api_endpoint.id_UNIQUE...
DROP INDEX id_UNIQUE ON sec_api_endpoint;


-- deployment: Dropping sec_api_endpoint...
DROP TABLE sec_api_endpoint;


-- deployment: Dropping sale_order_items.id_UNIQUE...
DROP INDEX id_UNIQUE ON sale_order_items;


-- deployment: Dropping sale_order_items...
DROP TABLE sale_order_items;


-- deployment: Dropping sale_order.order_num...
DROP INDEX order_num ON sale_order;


-- deployment: Dropping sale_order.id_UNIQUE...
DROP INDEX id_UNIQUE ON sale_order;


-- deployment: Dropping sale_order...
DROP TABLE sale_order;


-- deployment: Dropping region_master.region_code...
DROP INDEX region_code ON region_master;


-- deployment: Dropping region_master.code...
DROP INDEX code ON region_master;


-- deployment: Dropping region_master...
DROP TABLE region_master;


-- deployment: Dropping qrtz_triggers.FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS...
DROP INDEX FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS ON qrtz_triggers;


-- deployment: Dropping qrtz_triggers...
DROP TABLE qrtz_triggers;


-- deployment: Dropping product_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON product_master;


-- deployment: Dropping product_master...
DROP TABLE product_master;


-- deployment: Dropping plan_tier_feature_map.UNQ_plan_tire_feature...
DROP INDEX UNQ_plan_tire_feature ON plan_tier_feature_map;


-- deployment: Dropping plan_tier_feature_map...
DROP TABLE plan_tier_feature_map;


-- deployment: Dropping op_eprescription.id...
DROP INDEX id ON op_eprescription;


-- deployment: Dropping op_eprescription...
DROP TABLE op_eprescription;


-- deployment: Dropping op_consultation_notes.id...
DROP INDEX id ON op_consultation_notes;


-- deployment: Dropping op_consultation_notes...
DROP TABLE op_consultation_notes;


-- deployment: Dropping op_consultation.id...
DROP INDEX id ON op_consultation;


-- deployment: Dropping op_consultation...
DROP TABLE op_consultation;


-- deployment: Dropping notif_template_object.id_UNIQUE...
DROP INDEX id_UNIQUE ON notif_template_object;


-- deployment: Dropping notif_template_object...
DROP TABLE notif_template_object;


-- deployment: Dropping notif_template_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON notif_template_master;


-- deployment: Dropping notif_template_master.code_UNIQUE...
DROP INDEX code_UNIQUE ON notif_template_master;


-- deployment: Dropping notif_template_master...
DROP TABLE notif_template_master;


-- deployment: Dropping notif_otp_record.txn_id_UNIQUE...
DROP INDEX txn_id_UNIQUE ON notif_otp_record;


-- deployment: Dropping notif_otp_record...
DROP TABLE notif_otp_record;


-- deployment: Dropping notif_notification_txn.id_UNIQUE...
DROP INDEX id_UNIQUE ON notif_notification_txn;


-- deployment: Dropping notif_notification_txn...
DROP TABLE notif_notification_txn;


-- deployment: Dropping notif_email_verification_txn.id_UNIQUE...
DROP INDEX id_UNIQUE ON notif_email_verification_txn;


-- deployment: Dropping notif_email_verification_txn...
DROP TABLE notif_email_verification_txn;


-- deployment: Dropping notif_email_recipients.id_UNIQUE...
DROP INDEX id_UNIQUE ON notif_email_recipients;


-- deployment: Dropping notif_email_recipients...
DROP TABLE notif_email_recipients;


-- deployment: Dropping notif_device_usage.id_UNIQUE...
DROP INDEX id_UNIQUE ON notif_device_usage;


-- deployment: Dropping notif_device_usage...
DROP TABLE notif_device_usage;


-- deployment: Dropping notif_device_token.id_UNIQUE...
DROP INDEX id_UNIQUE ON notif_device_token;


-- deployment: Dropping notif_device_token.fcm_token_UNIQUE...
DROP INDEX fcm_token_UNIQUE ON notif_device_token;


-- deployment: Dropping notif_device_token...
DROP TABLE notif_device_token;


-- deployment: Dropping medicine_form.form_code...
DROP INDEX form_code ON medicine_form;


-- deployment: Dropping medicine_form...
DROP TABLE medicine_form;


-- deployment: Dropping loyalty_points_txn.id...
DROP INDEX id ON loyalty_points_txn;


-- deployment: Dropping loyalty_points_txn...
DROP TABLE loyalty_points_txn;


-- deployment: Dropping loyalty_points_transfer_type.id...
DROP INDEX id ON loyalty_points_transfer_type;


-- deployment: Dropping loyalty_points_transfer_type...
DROP TABLE loyalty_points_transfer_type;


-- deployment: Dropping loyalty_points_summary.id...
DROP INDEX id ON loyalty_points_summary;


-- deployment: Dropping loyalty_points_summary...
DROP TABLE loyalty_points_summary;


-- deployment: Dropping job_task_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON job_task_master;


-- deployment: Dropping job_task_master...
DROP TABLE job_task_master;


-- deployment: Dropping job_schedule_txns.txn_id_UNIQUE...
DROP INDEX txn_id_UNIQUE ON job_schedule_txns;


-- deployment: Dropping job_schedule_txns...
DROP TABLE job_schedule_txns;


-- deployment: Dropping job_schedule_master.schedule_code_UNIQUE...
DROP INDEX schedule_code_UNIQUE ON job_schedule_master;


-- deployment: Dropping job_schedule_master.job_name_UNIQUE...
DROP INDEX job_name_UNIQUE ON job_schedule_master;


-- deployment: Dropping job_schedule_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON job_schedule_master;


-- deployment: Dropping job_schedule_master...
DROP TABLE job_schedule_master;


-- deployment: Dropping item_restock_alert.id...
DROP INDEX id ON item_restock_alert;


-- deployment: Dropping item_restock_alert...
DROP TABLE item_restock_alert;


-- deployment: Dropping geo_polygon_coordinates.id_UNIQUE...
DROP INDEX id_UNIQUE ON geo_polygon_coordinates;


-- deployment: Dropping geo_polygon_coordinates...
DROP TABLE geo_polygon_coordinates;


-- deployment: Dropping epriscription_drug_plan_map.id...
DROP INDEX id ON epriscription_drug_plan_map;


-- deployment: Dropping epriscription_drug_plan_map...
DROP TABLE epriscription_drug_plan_map;


-- deployment: Dropping doctor_qualification.added_on_UNIQUE...
DROP INDEX added_on_UNIQUE ON doctor_qualification;


-- deployment: Dropping doctor_qualification...
DROP TABLE doctor_qualification;


-- deployment: Dropping doctor_master.phone_number...
DROP INDEX phone_number ON doctor_master;


-- deployment: Dropping doctor_master.email...
DROP INDEX email ON doctor_master;


-- deployment: Dropping doctor_master...
DROP TABLE doctor_master;


-- deployment: Dropping delivery_boy.id_UNIQUE...
DROP INDEX id_UNIQUE ON delivery_boy;


-- deployment: Dropping delivery_boy.email...
DROP INDEX email ON delivery_boy;


-- deployment: Dropping delivery_boy...
DROP TABLE delivery_boy;


-- deployment: Dropping customer_water_intake_summary.id...
DROP INDEX id ON customer_water_intake_summary;


-- deployment: Dropping customer_water_intake_summary...
DROP TABLE customer_water_intake_summary;


-- deployment: Dropping customer_water_intake_plan.id...
DROP INDEX id ON customer_water_intake_plan;


-- deployment: Dropping customer_water_intake_plan...
DROP TABLE customer_water_intake_plan;


-- deployment: Dropping customer_water_intake_details.id...
DROP INDEX id ON customer_water_intake_details;


-- deployment: Dropping customer_water_intake_details...
DROP TABLE customer_water_intake_details;


-- deployment: Dropping customer_wallet_txn.id...
DROP INDEX id ON customer_wallet_txn;


-- deployment: Dropping customer_wallet_txn...
DROP TABLE customer_wallet_txn;


-- deployment: Dropping customer_wallet_summary.id...
DROP INDEX id ON customer_wallet_summary;


-- deployment: Dropping customer_wallet_summary...
DROP TABLE customer_wallet_summary;


-- deployment: Dropping customer_relations.id_UNIQUE...
DROP INDEX id_UNIQUE ON customer_relations;


-- deployment: Dropping customer_relations...
DROP TABLE customer_relations;


-- deployment: Dropping customer_referral.id_UNIQUE...
DROP INDEX id_UNIQUE ON customer_referral;


-- deployment: Dropping customer_referral...
DROP TABLE customer_referral;


-- deployment: Dropping customer_prescription_uploads.id...
DROP INDEX id ON customer_prescription_uploads;


-- deployment: Dropping customer_prescription_uploads...
DROP TABLE customer_prescription_uploads;


-- deployment: Dropping customer_master.username_UNIQUE...
DROP INDEX username_UNIQUE ON customer_master;


-- deployment: Dropping customer_master...
DROP TABLE customer_master;


-- deployment: Dropping customer_bmi_profile.id...
DROP INDEX id ON customer_bmi_profile;


-- deployment: Dropping customer_bmi_profile...
DROP TABLE customer_bmi_profile;


-- deployment: Dropping cpg_workflow.id_UNIQUE...
DROP INDEX id_UNIQUE ON cpg_workflow;


-- deployment: Dropping cpg_workflow...
DROP TABLE cpg_workflow;


-- deployment: Dropping cpg_wallet_type.code...
DROP INDEX code ON cpg_wallet_type;


-- deployment: Dropping cpg_wallet_type...
DROP TABLE cpg_wallet_type;


-- deployment: Dropping cpg_wallet_bank_log.id...
DROP INDEX id ON cpg_wallet_bank_log;


-- deployment: Dropping cpg_wallet_bank_log...
DROP TABLE cpg_wallet_bank_log;


-- deployment: Dropping cpg_referral_wallet_type.code...
DROP INDEX code ON cpg_referral_wallet_type;


-- deployment: Dropping cpg_referral_wallet_type...
DROP TABLE cpg_referral_wallet_type;


-- deployment: Dropping cpg_payout.id_UNIQUE...
DROP INDEX id_UNIQUE ON cpg_payout;


-- deployment: Dropping cpg_payout...
DROP TABLE cpg_payout;


-- deployment: Dropping cpg_payment_link_data.id_UNIQUE...
DROP INDEX id_UNIQUE ON cpg_payment_link_data;


-- deployment: Dropping cpg_payment_link_data...
DROP TABLE cpg_payment_link_data;


-- deployment: Dropping cpg_payment.payment_id_UNIQUE...
DROP INDEX payment_id_UNIQUE ON cpg_payment;


-- deployment: Dropping cpg_payment.id_UNIQUE...
DROP INDEX id_UNIQUE ON cpg_payment;


-- deployment: Dropping cpg_payment...
DROP TABLE cpg_payment;


-- deployment: Dropping cpg_order.id_UNIQUE...
DROP INDEX id_UNIQUE ON cpg_order;


-- deployment: Dropping cpg_order...
DROP TABLE cpg_order;


-- deployment: Dropping code_master.code_UNIQUE...
DROP INDEX code_UNIQUE ON code_master;


-- deployment: Dropping code_master...
DROP TABLE code_master;


-- deployment: Dropping codedetails_master.code_parent_fk...
DROP INDEX code_parent_fk ON codedetails_master;


-- deployment: Dropping codedetails_master...
DROP TABLE codedetails_master;


-- deployment: Dropping chatbot_question.id_UNIQUE...
DROP INDEX id_UNIQUE ON chatbot_question;


-- deployment: Dropping chatbot_question...
DROP TABLE chatbot_question;


-- deployment: Dropping cdn_file_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON cdn_file_master;


-- deployment: Dropping cdn_file_master...
DROP TABLE cdn_file_master;


-- deployment: Dropping cdn_directory.id_UNIQUE...
DROP INDEX id_UNIQUE ON cdn_directory;


-- deployment: Dropping cdn_directory...
DROP TABLE cdn_directory;


-- deployment: Dropping cart_item.id_UNIQUE...
DROP INDEX id_UNIQUE ON cart_item;


-- deployment: Dropping cart_item...
DROP TABLE cart_item;


-- deployment: Dropping cart.id_UNIQUE...
DROP INDEX id_UNIQUE ON cart;


-- deployment: Dropping cart...
DROP TABLE cart;


-- deployment: Dropping call_records.id_UNIQUE...
DROP INDEX id_UNIQUE ON call_records;


-- deployment: Dropping call_records...
DROP TABLE call_records;


-- deployment: Dropping breathe_daily_summary.id_UNIQUE...
DROP INDEX id_UNIQUE ON breathe_daily_summary;


-- deployment: Dropping breathe_daily_summary...
DROP TABLE breathe_daily_summary;


-- deployment: Dropping breathe_challenge_tnx.id_UNIQUE...
DROP INDEX id_UNIQUE ON breathe_challenge_tnx;


-- deployment: Dropping breathe_challenge_tnx...
DROP TABLE breathe_challenge_tnx;


-- deployment: Dropping breathe_activity.id_UNIQUE...
DROP INDEX id_UNIQUE ON breathe_activity;


-- deployment: Dropping breathe_activity...
DROP TABLE breathe_activity;


-- deployment: Dropping audit_transaction_audit.txn_id...
DROP INDEX txn_id ON audit_transaction_audit;


-- deployment: Dropping audit_transaction_audit...
DROP TABLE audit_transaction_audit;


-- deployment: Dropping audit_session_audit.token_UNIQUE...
DROP INDEX token_UNIQUE ON audit_session_audit;


-- deployment: Dropping audit_session_audit.id_UNIQUE...
DROP INDEX id_UNIQUE ON audit_session_audit;


-- deployment: Dropping audit_session_audit...
DROP TABLE audit_session_audit;


-- deployment: Dropping audit_req_res_log.id_UNIQUE...
DROP INDEX id_UNIQUE ON audit_req_res_log;


-- deployment: Dropping audit_req_res_log...
DROP TABLE audit_req_res_log;


-- deployment: Dropping audit_exception_log.id_UNIQUE...
DROP INDEX id_UNIQUE ON audit_exception_log;


-- deployment: Dropping audit_exception_log...
DROP TABLE audit_exception_log;


-- deployment: Dropping audit_error_exceptions.id_UNIQUE...
DROP INDEX id_UNIQUE ON audit_error_exceptions;


-- deployment: Dropping audit_error_exceptions.composite_unique_key...
DROP INDEX composite_unique_key ON audit_error_exceptions;


-- deployment: Dropping audit_error_exceptions...
DROP TABLE audit_error_exceptions;


-- deployment: Dropping ambulance_master.vehicle_number...
DROP INDEX vehicle_number ON ambulance_master;


-- deployment: Dropping ambulance_master...
DROP TABLE ambulance_master;


-- deployment: Dropping ambulance_location.id_UNIQUE...
DROP INDEX id_UNIQUE ON ambulance_location;


-- deployment: Dropping ambulance_location...
DROP TABLE ambulance_location;


-- deployment: Dropping address_master.id_UNIQUE...
DROP INDEX id_UNIQUE ON address_master;


-- deployment: Dropping address_master...
DROP TABLE address_master;

