-- Script generated by Redgate Compare v1.48.1.2539


-- deployment: Creating dev...
CREATE TABLE dev (
    id int NOT NULL,
    title varchar(45) NULL
);
ALTER TABLE dev ADD PRIMARY KEY (id);


-- deployment: Creating dev.id_UNIQUE...
CREATE UNIQUE INDEX id_UNIQUE USING BTREE ON dev(id);

